Repository jekyll/jekyll, pull requests merged in 2018-02, with the labels that each got.

#6668 Test against Ruby 2.5 on AppVeyor
  appveyor.yml
Labels: tests

#6776 Codeclimate: exclude livereload.js
  .codeclimate.yml
Labels: meta

#6779 Fix documentation for `{{ page.excerpt }}`
  docs/_docs/posts.md
  docs/_docs/variables.md
Labels: documentation

#6775 Update docs on permalink configuration
  docs/_docs/permalinks.md
Labels: documentation

#6777 Add a cucumber feature to test link tag
  features/link_tag.feature
  features/step_definitions.rb
Labels: tests

#6784 Fix theme gem feature
  features/step_definitions.rb
  features/theme_gem.feature
Labels: tests, themes

#6790 Say hello to Jekyll's New Lead Developer
  docs/_posts/2018-02-19-meet-jekyll-s-new-lead-developer.markdown
  docs/team/index.md
Labels: documentation

#6792 Always load Google Fonts over HTTPS
  docs/_includes/top.html
Labels: documentation

#6794 Add reference to Liquid to plugin docs
  docs/_docs/plugins.md
Labels: documentation

#6736 Replace simple regex with equivalent Ruby methods
  benchmark/sanitize-url.rb
  lib/jekyll/document.rb
  lib/jekyll/static_file.rb
  lib/jekyll/theme_builder.rb
  lib/jekyll/url.rb
Labels: internal, refactor

#6681 Allow Jekyll Doctor to detect stray posts dir
  lib/jekyll/commands/doctor.rb
Labels: enhancement

#6724 Append appropriate closing tag to Liquid block in an excerpt
  lib/jekyll/excerpt.rb
  test/source/_posts/2018-01-28-closed-liquid-block-excerpt.markdown
  test/source/_posts/2018-01-28-open-liquid-block-excerpt.markdown
  test/test_excerpt.rb
  test/test_generated_site.rb
Labels: fix

#6807 always load analytics.js over HTTPS
  docs/_includes/analytics.html
Labels: site

#6802 add missing step for gem-based theme conversion
  docs/_docs/themes.md
Labels: documentation :book:, themes :art:

#6808 Memoize helper methods in site-cleaner
  lib/jekyll/cleaner.rb
  lib/jekyll/site.rb
Labels: optimization :zap:

#6735 Bypass rendering via Liquid unless required
  benchmark/conditional_liquid.rb
  lib/jekyll/convertible.rb
  lib/jekyll/document.rb
  lib/jekyll/renderer.rb
  lib/jekyll/utils.rb
Labels: optimization :zap:

#6767 Compute document's relative_path faster
  benchmark/native-vs-pathutil-relative
  lib/jekyll/document.rb
Labels: optimization :zap:

#6759 Create a single instance of PostReader per site
  lib/jekyll/reader.rb
Labels: optimization :zap:
