Repository jekyll/jekyll, pull requests merged in 2018-08, with the labels that each got.

#7143 Prepare docs for sponsoring
  docs/_data/sponsors.yml
  docs/_docs/contributing.md
  docs/_includes/footer.html
  docs/_posts/2018-08-01-jekyll-sponsoring.markdown
  docs/_sass/_style.scss
  docs/img/forestry-logo.png
Labels: documentation

#7171 Fix links in Code Climate badges
  README.markdown
Labels: meta

#7179 Add info how to deploy using pre-push git hook
  docs/_docs/deployment-methods.md
Labels: documentation

#7169 Add Cache class
  docs/_tutorials/cache_api.md
  lib/jekyll.rb
  lib/jekyll/cache.rb
  lib/jekyll/site.rb
  lib/site_template/.gitignore
  lib/theme_template/gitignore.erb
  test/test_site.rb
Labels: feature, needs-tests, optimization :zap:

#7189 Replace regex arg to :gsub with a string arg
  lib/jekyll/tags/include.rb
Labels: fix, internal

#6854 Add support for `*.xhtml` files
  lib/jekyll/commands/serve.rb
  lib/jekyll/commands/serve/servlet.rb
  test/fixtures/webrick/bar/foo.xhtml
  test/test_commands_serve_servlet.rb
Labels: enhancement, priority 4 (maybe)
