Repository jekyll/jekyll, pull requests merged in 2018-10, with the labels that each got.

#7289 Document converter methods
  lib/jekyll/converters/identity.rb
  lib/jekyll/converters/markdown.rb
  lib/jekyll/converters/smartypants.rb
Labels: hacktoberfest :beers:

#7291 Docs: Add link tag to item in RSS template
  docs/_tutorials/convert-existing-site-to-jekyll.md
Labels: documentation

#7159 Cache converted markdown
  lib/jekyll/converters/markdown.rb
  test/test_kramdown.rb
Labels: enhancement, optimization :zap:, priority 2 (should)

#7183 Cache converter in renderer
  lib/jekyll/renderer.rb
Labels: optimization :zap:, priority 2 (should)

#7190 Cache: Do not dump undumpable objects
  lib/jekyll/cache.rb
Labels: enhancement, priority 2 (should)

#7136 Optimize rendering Liquid templates
  docs/_docs/upgrading/3-to-4.md
  lib/jekyll/liquid_renderer.rb
  lib/jekyll/liquid_renderer/file.rb
  lib/jekyll/tags/include.rb
  lib/jekyll/tags/link.rb
Labels: breaking-change, optimization :zap:

#7299 Automatically load _config.toml
  docs/_docs/configuration.md
  lib/jekyll/configuration.rb
  test/test_configuration.rb
Labels: enhancement

#7312 CI(Appveyor): shallow clone with 5 last commits
  appveyor.yml
Labels: tests, windows

#7325 Add a link to Giraffe Academy's tutorial
  README.markdown
Labels: documentation

#7302 Skip processing posts that can not be read
  lib/jekyll/readers/post_reader.rb
  test/source/_posts/2008-02-03-wrong-extension.yml
  test/test_post_reader.rb
  test/test_site.rb
Labels: enhancement

#7326 Revert "Cache converter in renderer"
  History.markdown
  lib/jekyll/renderer.rb
Labels: fix

#7319 Add Tidelift to site sponsors
  docs/_includes/footer.html
  docs/img/tidelift-logo.png
Labels: discussion, site

#7333 docs: list all standard liquid filters
  docs/_docs/liquid/filters.md
Labels: documentation

#7334 Liquid templating to DRY content
  docs/_docs/liquid/filters.md
Labels: documentation

#7335 Document Jekyll Filters with YAML data
  docs/_data/jekyll_filters.yml
  docs/_docs/liquid/filters.md
Labels: documentation

#7336 docs: Page variables as YAML data
  docs/_data/jekyll_variables.yml
  docs/_docs/variables.md
Labels: documentation

#7338 Bump RuboCop to v0.60.x
  Gemfile
  lib/jekyll/cleaner.rb
  lib/jekyll/commands/serve/servlet.rb
  lib/jekyll/document.rb
  lib/jekyll/excerpt.rb
  lib/jekyll/frontmatter_defaults.rb
  lib/jekyll/tags/highlight.rb
  lib/jekyll/tags/include.rb
  lib/jekyll/tags/post_url.rb
  lib/jekyll/utils/ansi.rb
Labels: dependency, internal

#7276 Memoize Site#post_attr_hash
  lib/jekyll/site.rb
Labels: fix, optimization :zap:

#7316 Measure the no. of times a template gets rendered
  lib/jekyll/liquid_renderer.rb
  lib/jekyll/liquid_renderer/file.rb
Labels: fix

#7304 Load config file from within current theme-gem
  docs/_docs/themes.md
  features/theme_configuration.feature
  lib/jekyll/site.rb
  test/fixtures/test-theme/_config.yml
  test/test_site.rb
Labels: feature, themes :art:

#7343 docs: minimize rendering count
  docs/_includes/docs_contents.html
  docs/_includes/docs_contents_mobile.html
  docs/_includes/docs_option.html
  docs/_includes/docs_ul.html
Labels: documentation, optimization :zap:

#7273 Memoize the return value of Site#documents
  lib/jekyll/site.rb
Labels: fix, optimization :zap:
