Repository jekyll/jekyll, pull requests merged in 2018-12, with the labels that each got.

#7405 link site to sponsor listing in readme
  README.markdown
  docs/_data/sponsors.yml
  docs/_includes/footer.html
  docs/img/cloudcannon-logo.png
  docs/img/forestry-logo.png
  docs/img/icons8-logo.png
  docs/img/siteleaf-logo.png
  docs/img/tidelift-logo.png
  docs/img/vpsserver-logo.png
Labels: site

#7420 [Docs] Fix BASH code-block in ubuntu.md
  docs/_docs/installation/ubuntu.md
Labels: documentation

#7419 Theme gems: ensure directories aren't symlinks
  Gemfile
  lib/jekyll/theme.rb
  test/fixtures/test-theme-symlink/test-theme-symlink.gemspec
  test/test_theme_assets_reader.rb
Labels: backport-candidate, security, themes :art:

#7404 Documents should be able to render their date
  lib/jekyll/drops/document_drop.rb
  lib/jekyll/drops/excerpt_drop.rb
  test/test_document.rb
Labels: fix

#7422 Add a custom inspect string for StaticFile objects
  lib/jekyll/static_file.rb
  test/test_static_file.rb
Labels: enhancement

#7157 Reduce array traversal in Jekyll::Reader
  lib/jekyll/reader.rb
Labels: refactor

#7429 Create symlink only if target is accessible
  test/helper.rb
  test/test_layout_reader.rb
Labels: backport-candidate, internal, tests

#7437 Lock JRuby builds on Travis CI to i18n-1.2.x
  Gemfile
Labels: tests
