Repository jekyll/jekyll, pull requests merged in 2018-04, with the labels that each got.

#6898 doc: add liquid tag plugin jekyll-onebox for html previews
  docs/_docs/plugins.md
Labels: documentation

#6907 Assert existence of <collection>.files
  test/test_collections.rb
Labels: tests

#6915 Bump Rubocop to 0.54.x
  .rubocop.yml
  Gemfile
  lib/jekyll/command.rb
  lib/jekyll/commands/serve.rb
  lib/jekyll/commands/serve/live_reload_reactor.rb
  lib/jekyll/commands/serve/servlet.rb
  lib/jekyll/commands/serve/websockets.rb
  lib/jekyll/converters/markdown/kramdown_parser.rb
  lib/jekyll/converters/markdown/rdiscount_parser.rb
  lib/jekyll/convertible.rb
  lib/jekyll/entry_filter.rb
  lib/jekyll/liquid_renderer.rb
  lib/jekyll/liquid_renderer/table.rb
  lib/jekyll/utils/platforms.rb
  test/test_commands_serve.rb
  test/test_filters.rb
Labels: internal

#6917 Regenerate unconditionally unless its an incremental build
  lib/jekyll/regenerator.rb
Labels: incremental-regeneration, optimization :zap:

#6910 Centralize require statements
  benchmark/local-require
  lib/jekyll.rb
  lib/jekyll/cleaner.rb
  lib/jekyll/commands/doctor.rb
  lib/jekyll/commands/serve/live_reload_reactor.rb
  lib/jekyll/converters/markdown/kramdown_parser.rb
  lib/jekyll/convertible.rb
  lib/jekyll/drops/drop.rb
  lib/jekyll/drops/jekyll_drop.rb
  lib/jekyll/filters.rb
  lib/jekyll/filters/url_filters.rb
  lib/jekyll/reader.rb
  lib/jekyll/site.rb
  lib/jekyll/url.rb
  lib/jekyll/utils/rouge.rb
Labels: fix, internal, optimization :zap:

#6818 `include_relative` tag should find related documents in collections gathered within custom `collections_dir`
  features/collections_dir.feature
  lib/jekyll/tags/include.rb
Labels: fix

#6856 Store and retrieve converter instances for Jekyll::Filters via a hash
  lib/jekyll/filters.rb
  lib/jekyll/site.rb
Labels: enhancement, optimization :zap:

#6868 Implement a cache within the `where` filter
  lib/jekyll/filters.rb
Labels: optimization :zap:

#6891 Handle liquid tags in excerpts robustly
  lib/jekyll/excerpt.rb
  test/source/_posts/2018-01-28-closed-liquid-block-excerpt.markdown
Labels: fix

#6841 Optimize computing filename in LiquidRenderer
  lib/jekyll/liquid_renderer.rb
Labels: optimization :zap:

#6782 add Arch Linux instalation troubleshoot
  docs/_docs/troubleshooting.md
Labels: documentation

#6881 Docs: Install Jekyll on macOS
  docs/_docs/history.md
  docs/_docs/installation.md
Labels: documentation

#6928 Correct errors in troubleshooting.md
  docs/_docs/troubleshooting.md
Labels: documentation

#6822 Refactor private method `HighlightBlock#parse_options`
  lib/jekyll/tags/highlight.rb
Labels: internal

#6933 Update index.md
  docs/_docs/index.md
Labels: documentation

#6885 Allow front matter defaults to be applied properly to documents gathered under custom `collections_dir`
  features/collections_dir.feature
  features/step_definitions.rb
  lib/jekyll/frontmatter_defaults.rb
Labels: fix

#6925 Add Installation Instructions for Ubuntu
  docs/_docs/installation.md
Labels: documentation

#6945 Fix rendering Liquid constructs in excerpts
  features/post_excerpts.feature
  lib/jekyll/excerpt.rb
Labels: fix

#6927 WIP: Do not advise users to install Jekyll outside of Bundler
  docs/_docs/quickstart.md
  docs/index.html
Labels: discussion

#6781 Don't prompt for sudo when installing with Ubuntu WSL
  docs/_docs/windows.md
Labels: documentation
