Repository jekyll/jekyll, pull requests merged in 2018-05, with the labels that each got.

#6951 Memoize computing excerpt's relative_path
  lib/jekyll/excerpt.rb
Labels: fix

#6959 Liquify documents unless published == false
  features/collections.feature
  lib/jekyll/collection.rb
Labels: fix

#6956 Add version number for group_by_exp doc
  docs/_docs/templates.md
Labels: documentation

#6976 yajl-ruby update to v1.4.0
  Gemfile
Labels: dependency

#6977 We are not using Ruby 2.2 anymore
  Gemfile
Labels: feature

#6926 Update Windows install docs
  docs/_docs/windows.md
Labels: documentation, windows

#6269 Liquefied link tag
  docs/_docs/templates.md
  lib/jekyll/tags/link.rb
  test/test_tags.rb
Labels: enhancement

#6551 Suggest re-running command with --trace on fail
  lib/jekyll/command.rb
  lib/jekyll/commands/build.rb
  lib/jekyll/commands/serve.rb
Labels: friction

#6978 Drop support for older versions of Rouge
  .travis.yml
  Gemfile
  jekyll.gemspec
  lib/jekyll/converters/markdown/redcarpet_parser.rb
  lib/jekyll/tags/highlight.rb
  lib/jekyll/utils.rb
  lib/jekyll/utils/rouge.rb
  test/test_kramdown.rb
  test/test_tags.rb
Labels: dependency

#6990 Remove documentation for using Redcarpet
  docs/_docs/configuration.md
Labels: documentation

#7003 Textile is only supported through a converter plugin
  docs/_docs/pagination.md
  docs/_docs/structure.md
  docs/_docs/upgrading/2-to-3.md
  docs/index.html
Labels: documentation

#6985 Document that _drafts need to be contained within the custom collection directory
  docs/_docs/collections.md
Labels: documentation

#7007 Load Rouge for TestKramdown
  test/test_kramdown.rb
Labels: fix, tests

#6768 Useless privates removed
  .rubocop.yml
  lib/jekyll/collection.rb
  lib/jekyll/commands/serve.rb
  lib/jekyll/commands/serve/live_reload_reactor.rb
  lib/jekyll/commands/serve/servlet.rb
  lib/jekyll/configuration.rb
  lib/jekyll/converters/markdown.rb
  lib/jekyll/converters/markdown/kramdown_parser.rb
  lib/jekyll/document.rb
  lib/jekyll/filters.rb
  lib/jekyll/filters/date_filters.rb
  lib/jekyll/filters/grouping_filters.rb
  lib/jekyll/regenerator.rb
  lib/jekyll/renderer.rb
  lib/jekyll/site.rb
  lib/jekyll/utils.rb
  lib/jekyll/utils/internet.rb
Labels: accepted

#7027 Fix --unpublished not affecting collection documents
  features/collections.feature
  lib/jekyll/collection.rb
Labels: fix

#7031 Updated to supported version
  docs/_docs/windows.md
Labels: documentation, windows

#7037 Clarify definition of 'draft'
  docs/_docs/drafts.md
Labels: documentation
