Repository jekyll/jekyll, pull requests merged in 2018-03, with the labels that each got.

#6813 Rewrite `script/rubyprof` as a Ruby script
  script/rubyprof
Labels: internal

#5195 Add debug output to theme rendering
  lib/jekyll/renderer.rb
  lib/jekyll/theme.rb
Labels: themes :art:

#6773 Allow date filters to output ordinal days
  docs/_docs/templates.md
  lib/jekyll/filters.rb
  lib/jekyll/filters/date_filters.rb
  test/test_filters.rb
Labels: enhancement

#6819 Delegated methods after `private` keyword are meant to be private
  lib/jekyll/drops/collection_drop.rb
  lib/jekyll/drops/document_drop.rb
  lib/jekyll/drops/site_drop.rb
  lib/jekyll/drops/static_file_drop.rb
Labels: fix

#6610 Change regex to sanitize and normalize filenames passed to LiquidRenderer
  lib/jekyll/liquid_renderer.rb
  script/default-site
Labels: profiling

#6795 Improve handling non-default collection documents rendering and writing
  docs/_docs/collections.md
  features/collections.feature
  lib/jekyll/collection.rb
  lib/jekyll/document.rb
  test/test_document.rb
Labels: fix, optimization :zap:

#6839 fix minitest deprecation warning in test
  test/test_site.rb
Labels: tests

#6726 Allow passing :strict_variables and :strict_filters options to Liquid's renderer
  docs/_docs/configuration.md
  features/rendering.feature
  lib/jekyll/configuration.rb
  lib/jekyll/renderer.rb
Labels: enhancement

#6809 Memoize `Site#site_data`
  lib/jekyll/site.rb
Labels: optimization :zap:

#6814 Memoize document output extension
  lib/jekyll/document.rb
Labels: optimization :zap:

#6846 Assign and use Liquid variables in templates
  docs/_includes/news_item.html
  docs/_layouts/news_item.html
Labels: site

#6828 Add Bundler Installation Instructions
  docs/_data/tutorials.yml
  docs/_tutorials/using-jekyll-with-bundler.md
Labels: documentation

#6740 Access document permalink attribute efficiently
  lib/jekyll/renderer.rb
Labels: fix, internal

#6848 Improve regex usage in `Tags::IncludeTag`
  features/include_tag.feature
  lib/jekyll/tags/include.rb
Labels: enhancement

#6858 Fix passing multiline params to include tag when using the variable syntax
  lib/jekyll/tags/include.rb
  test/test_tags.rb
Labels: fix

#6860 Minimize array allocations in the `where` filter
  lib/jekyll/filters.rb
Labels: internal
