Repository jekyll/jekyll, pull requests merged in 2018-09, with the labels that each got.

#7213 Add cucumber feature to test include_relative tag
  features/include_relative_tag.feature
Labels: internal, tests

#7224 3.7.x: EntryFilter#filter symlink fix
  lib/jekyll/entry_filter.rb
  test/source/symlink-test/symlinked-file-outside-source
  test/test_entry_filter.rb
  test/test_layout_reader.rb
Labels: security

#7226 Security: fix `include` bypass of `EntryFilter#filter` symlink check
  lib/jekyll/entry_filter.rb
  test/source/symlink-test/symlinked-file-outside-source
  test/test_entry_filter.rb
  test/test_layout_reader.rb
Labels: security

#6888 Cache matched defaults sets for given parameters
  lib/jekyll/frontmatter_defaults.rb
Labels: enhancement, optimization :zap:

#7229 3.6.x: security: fix `include` bypass of `EntryFilter#filter` symlink check
  lib/jekyll/entry_filter.rb
  test/source/symlink-test/symlinked-file-outside-source
  test/test_entry_filter.rb
  test/test_layout_reader.rb
Labels: :rewind: backport, security

#7263 Check if scope applies to type before given path
  lib/jekyll/frontmatter_defaults.rb
Labels: Front Matter Defaults, fix

#7268 Update 10-deployment.md
  docs/_docs/step-by-step/10-deployment.md
Labels: documentation

#7269 Add more issue template(s) and pull request template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: github

#7278 update yajl-ruby
  Gemfile
Labels: dependency

#7118 Drop support for pygments as syntax-highlighter
  Gemfile
  docs/_docs/liquid/tags.md
  docs/_tutorials/orderofinterpretation.md
  features/site_configuration.feature
  lib/jekyll/tags/highlight.rb
  test/test_tags.rb
Labels: pinned, priority 2 (should)

#7259 Add Release Post for v3.6.3, v3.7.4 and v3.8.4
  docs/_posts/2018-09-19-security-fixes-for-3-6-3-7-3-8.markdown
Labels: documentation, release

#7283 Docs: more inclusive writing
  .github/CONTRIBUTING.markdown
  History.markdown
  docs/_docs/code_of_conduct.md
  docs/_docs/collections.md
  docs/_docs/configuration/front-matter-defaults.md
  docs/_docs/continuous-integration/circleci.md
  docs/_docs/continuous-integration/travis-ci.md
  docs/_docs/contributing.md
  docs/_docs/deployment/manual.md
  docs/_docs/deployment/third-party.md
  docs/_docs/front-matter.md
  docs/_docs/github-pages.md
  docs/_docs/history.md
  docs/_docs/includes.md
  docs/_docs/maintaining/affinity-team-captain.md
  docs/_docs/pages.md
  docs/_docs/plugins/filters.md
  docs/_docs/plugins/hooks.md
  docs/_docs/plugins/installation.md
  docs/_docs/posts.md
  docs/_docs/static_files.md
  docs/_docs/step-by-step/08-blogging.md
  docs/_docs/support.md
  docs/_docs/themes.md
  docs/_docs/troubleshooting.md
  docs/_docs/upgrading/0-to-2.md
Labels: documentation
