Repository jekyll/jekyll, pull requests merged in 2018-07, with the labels that each got.

#7112 GitHub enables you to use themes from other repos
  docs/_docs/themes.md
Labels: documentation

#7095 Instructions to view theme’s files under Linux
  docs/_docs/themes.md
Labels: documentation

#7104 Fix tests to have "expected value" as the first argument passed to `assert_equal`
  test/test_document.rb
  test/test_excerpt_drop.rb
  test/test_filters.rb
  test/test_front_matter_defaults.rb
  test/test_page_without_a_file.rb
Labels: fix, tests

#7122 Add call to unused method `validate_options` in `commands/serve.rb`
  lib/jekyll/commands/serve.rb
Labels: fix

#7128 Fix Rubocop offences in test files
  .rubocop.yml
  test/helper.rb
  test/test_coffeescript.rb
  test/test_collections.rb
  test/test_command.rb
  test/test_commands_serve.rb
  test/test_configuration.rb
  test/test_convertible.rb
  test/test_doctor_command.rb
  test/test_document.rb
  test/test_drop.rb
  test/test_entry_filter.rb
  test/test_excerpt.rb
  test/test_filters.rb
  test/test_front_matter_defaults.rb
  test/test_generated_site.rb
  test/test_kramdown.rb
  test/test_layout_reader.rb
  test/test_liquid_extensions.rb
  test/test_page.rb
  test/test_page_without_a_file.rb
  test/test_plugin_manager.rb
  test/test_regenerator.rb
  test/test_related_posts.rb
  test/test_sass.rb
  test/test_site.rb
  test/test_site_drop.rb
  test/test_static_file.rb
  test/test_tags.rb
  test/test_utils.rb
Labels: tests

#6824 Disable Liquid via front matter
  features/post_data.feature
  lib/jekyll/convertible.rb
  lib/jekyll/document.rb
  test/fixtures/no_liquid.erb
  test/test_convertible.rb
Labels: feature, needs-documentation, priority 3 (could)

#7133 fix up refute_equal call
  test/test_collections.rb
Labels: tests

#7134 Fix incorrectly passed arguments to assert_equal
  test/test_ansi.rb
  test/test_collections.rb
  test/test_commands_serve.rb
  test/test_configuration.rb
  test/test_kramdown.rb
  test/test_liquid_extensions.rb
  test/test_regenerator.rb
Labels: tests

#7138 Update docs about post creation
  lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb
Labels: documentation

#7139 Add DEV Community's Jekyll tag to community page
  docs/help/index.md
Labels: documentation

#7140 Initialize upgrading doc for v4.0
  docs/_docs/upgrading/3-to-4.md
Labels: documentation

#7144 Lock Travis to Bundler-1.16.2
  .travis.yml
Labels: meta, tests

#7146 Do not process Liquid in post excerpt when disabled in front matter
  features/post_excerpts.feature
  lib/jekyll/excerpt.rb
Labels: fix

#7162 Add version badge for date filters with ordinal
  docs/_docs/templates.md
Labels: documentation
