Repository jekyll/jekyll, pull requests merged in 2018-11, with the labels that each got.

#7250 Re-implement handling Liquid blocks in excerpts
  lib/jekyll/excerpt.rb
  test/source/_posts/2018-01-28-closed-liquid-block-excerpt.markdown
  test/source/_posts/2018-01-28-open-liquid-block-excerpt.markdown
  test/test_excerpt.rb
Labels: backport-candidate, fix, priority 2 (should)

#6727 Incorporate `relative_url` filter in `link` tag
  features/link_tag.feature
  jekyll.gemspec
  lib/jekyll/tags/link.rb
Labels: breaking-change, priority 2 (should)

#7352 Backport #7250 to 3.8.x
  lib/jekyll/excerpt.rb
  test/source/_posts/2018-01-28-closed-liquid-block-excerpt.markdown
  test/source/_posts/2018-01-28-open-liquid-block-excerpt.markdown
  test/test_excerpt.rb
Labels: :rewind: backport, fix

#7359 Add documentation for custom tag blocks
  docs/_docs/plugins/tags.md
Labels: documentation

#7375 Upgrade liquid-c to v4.0
  Gemfile
Labels: dependency

#7381 Remove installation instructions with Homebrew
  docs/_docs/installation/macos.md
Labels: documentation

#6788 Only read layouts from source_dir or theme_dir
  lib/jekyll/readers/layout_reader.rb
  test/test_layout_reader.rb
Labels: breaking-change

#7365 Update excludes for CodeClimate Analyses
  .codeclimate.yml
Labels: meta

#7388 Site: Better Performance
  docs/_includes/top.html
  docs/_sass/_docsearch.scss
  docs/_sass/_fonts.scss
  docs/css/screen.scss
  docs/fonts/lato-v14-latin-300.woff
  docs/fonts/lato-v14-latin-300.woff2
  docs/fonts/lato-v14-latin-300italic.woff
  docs/fonts/lato-v14-latin-300italic.woff2
  docs/fonts/lato-v14-latin-700.woff
  docs/fonts/lato-v14-latin-700.woff2
  docs/fonts/lato-v14-latin-700italic.woff
  docs/fonts/lato-v14-latin-700italic.woff2
  docs/fonts/lato-v14-latin-900.woff
  docs/fonts/lato-v14-latin-900.woff2
  docs/fonts/lato-v14-latin-900italic.woff
  docs/fonts/lato-v14-latin-900italic.woff2
  docs/fonts/lato-v14-latin-italic.woff
  docs/fonts/lato-v14-latin-italic.woff2
  docs/fonts/lato-v14-latin-regular.woff
  docs/fonts/lato-v14-latin-regular.woff2
  docs/img/cloudcannon-logo.png
  docs/img/forestry-logo.png
  docs/img/icons8-logo.png
  docs/img/siteleaf-logo.png
  docs/img/tidelift-logo.png
Labels: documentation

#7395 adjust team page listings
  docs/pages/team.md
Labels: documentation

#7396 Update resources.md
  docs/pages/resources.md
Labels: documentation
