Repository jekyll/jekyll, pull requests merged in 2019-04, with the labels that each got.

#7607 Simplify couple of includes in the docs site
  docs/_includes/docs_contents.html
  docs/_includes/docs_contents_mobile.html
  docs/_includes/step-index.html
Labels: site

#7612 Bump tested version of JRuby to 9.2.7.0
  .travis.yml
  Gemfile
Labels: tests

#7610 Avoid generating empty classnames
  docs/_includes/mobile-nav-items.html
  docs/_includes/news_contents.html
  docs/_includes/primary-nav-items.html
  docs/_includes/tutorials_ul.html
Labels: site

#7614 Generate a "TOTAL" row for build-profile table
  lib/jekyll/liquid_renderer/table.rb
Labels: enhancement

#7561 Install Docs that Work on MacOS 10.14
  docs/_docs/installation/macos.md
Labels: documentation

#7592 Revert "Refactor `highlight` tag to behave like the `raw` tag"
  History.markdown
  docs/_docs/upgrading/3-to-4.md
  features/highlighting.feature
  jekyll.gemspec
  lib/jekyll/tags/highlight.rb
  test/test_tags.rb
Labels: priority 2 (should)

#7633 Fix broken include_relative usage in excerpt
  features/include_relative_tag.feature
  lib/jekyll/tags/include.rb
Labels: backport-candidate, fix
