Repository jekyll/jekyll, pull requests merged in 2019-05, with the labels that each got.

#7532 Refactor Jekyll::Cache
  features/cache.feature
  lib/jekyll/cache.rb
  lib/jekyll/site.rb
Labels: refactor

#7647 Docs: add version tags to new placeholders (#5981) for permalinks
  docs/_docs/permalinks.md
Labels: documentation

#7648 Solve "GitHub Page build failure" in 10-deployment.md
  docs/_docs/step-by-step/10-deployment.md
Labels: documentation

#7658 Initialize and reset glob_cache only as necessary
  lib/jekyll/frontmatter_defaults.rb
Labels: fix

#7654 Encode and unencode urls only as required
  lib/jekyll/url.rb
Labels: optimization :zap:

#7646 Profile allocations from a build session
  .travis.yml
  Gemfile
  appveyor.yml
  rake/profile.rake
  script/memprof
Labels: internal, profiling

#7625 Reduce allocations from Jekyll::Document instances
  lib/jekyll/document.rb
Labels: optimization :zap:

#7406 Add `type` attribute to Document instances
  lib/jekyll/document.rb
  lib/jekyll/excerpt.rb
  test/test_document.rb
  test/test_excerpt.rb
Labels: enhancement, optimization :zap:

#7653 Reduce allocations from where-filter
  lib/jekyll/filters.rb
Labels: optimization :zap:, refactor

#7609 Simplify assigning classname to docs' aside-links
  docs/_includes/docs_contents.html
Labels: site

#7684 Revert memoizing Site#docs_to_write and #documents
  lib/jekyll/site.rb
Labels: backport-candidate, fix

#7689 Backport #7684 for v3.8.x: Revert memoizing Site#docs_to_write and refactor #documents
  lib/jekyll/site.rb
Labels: :rewind: backport, fix
