Repository jekyll/jekyll, pull requests merged in 2019-03, with the labels that each got.

#7562 Lock use of TZInfo gem to v1.x
  Gemfile
  History.markdown
  docs/_docs/upgrading/3-to-4.md
  lib/jekyll/commands/new.rb
  lib/jekyll/utils/win_tz.rb
Labels: fix, windows

#7564 Improve handling sites without layouts
  docs/_docs/layouts.md
Labels: documentation

#7424 Backport #7419 for v3.8.x: Theme gems: ensure directories aren't symlinks
  Gemfile
  lib/jekyll/theme.rb
  test/fixtures/test-theme-symlink/test-theme-symlink.gemspec
  test/test_theme_assets_reader.rb
Labels: :rewind: backport, security

#7467 Backport #7382 for v3.8.x: Excerpt handling of custom and intermediate tags
  lib/jekyll/excerpt.rb
  test/source/_plugins/custom_block.rb
  test/source/_posts/2018-11-15-excerpt-liquid-block.md
  test/test_excerpt.rb
  test/test_generated_site.rb
Labels: :rewind: backport

#7567 Fix CI builds on older Ruby versions
  .travis.yml
  Gemfile
Labels: :rewind: backport, tests

#7572 Fix unnecessary allocations via StaticFileReader
  lib/jekyll/readers/static_file_reader.rb
Labels: fix

#6821 Refactor `highlight` tag to behave like the `raw` tag
  features/highlighting.feature
  jekyll.gemspec
  lib/jekyll/tags/highlight.rb
  test/test_tags.rb
Labels: breaking-change, enhancement, priority 2 (should)

#7345 Cache globbed paths in front matter defaults
  lib/jekyll/frontmatter_defaults.rb
  lib/jekyll/site.rb
Labels: Front Matter Defaults, fix, optimization :zap:

#7301 Cache computed item property
  lib/jekyll/filters.rb
Labels: optimization :zap:

#7498 Don't check if site URL is absolute if it is nil
  lib/jekyll/commands/doctor.rb
Labels: fix

#7566 Use communicative method parameters
  .rubocop.yml
  lib/jekyll/configuration.rb
  lib/jekyll/converters/smartypants.rb
Labels: fix

#7272 Avoid unnecessary duplication of pages array
  lib/jekyll/site.rb
Labels: fix

#7568 Escape valid special chars in a site's path name
  features/rendering.feature
  lib/jekyll/liquid_renderer.rb
Labels: backport-candidate, fix

#7492 Upgrade kramdown dependency to v2.x
  Gemfile
  docs/_docs/upgrading/3-to-4.md
  features/collections.feature
  jekyll.gemspec
  lib/jekyll/configuration.rb
  lib/jekyll/converters/markdown/kramdown_parser.rb
Labels: dependency, enhancement

#7519 Cleanup Markdown converter
  lib/jekyll/converters/markdown.rb
Labels: refactor

#7454 Feat: drop ruby 2.3
  .travis.yml
  appveyor.yml
  jekyll.gemspec
  test/test_commands_serve.rb
Labels: needs-documentation, priority 1 (must)

#7434 Replace `name` in Page#inspect with relative_path
  lib/jekyll/page.rb
  test/test_page_without_a_file.rb
Labels: fix

#7418 docs: mention CommonMark plugins
  docs/_docs/configuration/markdown.md
Labels: documentation

#7130 Scan `assert_equal` methods and rectify any offenses with a custom Rubocop cop
  rubocop/jekyll/assert_equal_literal_actual.rb
Labels: internal, tests

#7573 Backport #7568 for v3.8.x: Escape valid special chars in a site's path name
  features/rendering.feature
  lib/jekyll/liquid_renderer.rb
Labels: :rewind: backport, fix

#7577 Push Markdown link refs to excerpt only as required
  features/post_excerpts.feature
  lib/jekyll/excerpt.rb
Labels: fix

#7574 Release v4.0.0.pre.alpha1
  History.markdown
  docs/_config.yml
  docs/_docs/history.md
  docs/_docs/installation.md
  docs/_docs/installation/macos.md
  docs/_docs/liquid/tags.md
  docs/_docs/troubleshooting.md
  docs/_docs/upgrading.md
  docs/_docs/upgrading/3-to-4.md
  docs/_posts/2019-03-18-jekyll-4-0-0-pre-alpha1-released.markdown
  docs/_tutorials/cache_api.md
  jekyll.gemspec
  lib/jekyll/version.rb
Labels: release

#5981 ISO week date drops
  docs/_docs/permalinks.md
  lib/jekyll/configuration.rb
  lib/jekyll/drops/url_drop.rb
Labels: enhancement

#7580 Detect `nil` and empty values in objects with `where` filter
  docs/_docs/liquid/filters.md
  features/embed_filters.feature
  features/step_definitions.rb
  lib/jekyll/filters.rb
  test/test_filters.rb
Labels: enhancement

#7584 Remove Jekyll::Utils#strip_heredoc in favor of a Ruby > 2.3 built in
  features/step_definitions.rb
  lib/jekyll/commands/serve/servlet.rb
  lib/jekyll/utils.rb
  test/test_kramdown.rb
Labels: breaking-change

#7586 Add a Cucumber feature for post_url tag
  features/post_url_tag.feature
Labels: tests

#7589 Incorporate `relative_url` within `post_url` tag
  docs/_docs/upgrading/3-to-4.md
  docs/_sass/_style.scss
  features/post_url_tag.feature
  jekyll.gemspec
  lib/jekyll/tags/post_url.rb
Labels: breaking-change
