Repository jekyll/jekyll, pull requests merged in 2019-08, with the labels that each got.

#7732 Add PathManager class to cache interim paths
  lib/jekyll.rb
  lib/jekyll/entry_filter.rb
  lib/jekyll/page.rb
  lib/jekyll/path_manager.rb
  lib/jekyll/reader.rb
  lib/jekyll/tags/include.rb
Labels: feature, optimization :zap:

#7769 Fix: rubocop offenses
  lib/jekyll/excerpt.rb
  lib/jekyll/filters.rb
  lib/jekyll/readers/post_reader.rb
Labels: fix

#7440 Remove warnings and fixes for deprecated config
  docs/_docs/upgrading/3-to-4.md
  features/markdown.feature
  features/pagination.feature
  features/plugins.feature
  features/rendering.feature
  jekyll.gemspec
  lib/jekyll/configuration.rb
  test/test_configuration.rb
Labels: breaking-change

#7627 Delegate --profile tabulation to `terminal-table`
  jekyll.gemspec
  lib/jekyll/liquid_renderer/table.rb
  test/test_liquid_renderer.rb
Labels: dependency, needs-decision :thinking:, profiling

#7701 Use String#end_with? to check if entry is a backup
  lib/jekyll/entry_filter.rb
Labels: fix, optimization :zap:

#7290 Remove configuration of theme sass files from Core
  Gemfile
  features/rendering.feature
  features/theme.feature
  jekyll.gemspec
  lib/jekyll/theme.rb
  test/fixtures/test-theme/assets/style.scss
  test/test_filters.rb
  test/test_sass.rb
  test/test_site.rb
  test/test_theme.rb
  test/test_theme_assets_reader.rb
Labels: dependency, themes :art:

#7778 Use jekyll-sass-converter-2.0 by default
  Gemfile
  jekyll.gemspec
Labels: feature

#7786 Documentation for binary operators in where_exp
  docs/_docs/liquid/filters.md
Labels: documentation

#7792 Actually conditionally include liquid-c
  lib/jekyll.rb
Labels: fix

#7788 Test number_like regex on stringified property
  lib/jekyll/filters.rb
Labels: fix

#7782 Jekyll v4.0 release
  History.markdown
  docs/_config.yml
  docs/_docs/history.md
  docs/_posts/2019-08-19-jekyll-4-0-0-released.markdown
  docs/latest_version.txt
  lib/jekyll/version.rb
Labels: release

#7795 Update 2019-08-19-jekyll-4-0-0-released.markdown
  docs/_posts/2019-08-19-jekyll-4-0-0-released.markdown
Labels: site

#7793 Memoize absolute_url and relative_url filters
  lib/jekyll/filters/url_filters.rb
Labels: optimization :zap:

#7768 serve: add support for ECC certificates
  lib/jekyll/commands/serve.rb
Labels: enhancement
