Repository jekyll/jekyll, pull requests merged in 2019-10, with the labels that each got.

#7839 Fix RuboCop Performance offenses in test files
  test/test_document.rb
  test/test_filters.rb
Labels: internal, tests

#7873 clarify _config.yml/collections type
  docs/_docs/collections.md
Labels: documentation

#7883 Fix documentation comment for Jekyll::Converters::Identity
  lib/jekyll/converters/identity.rb
Labels: bug, fix
