Repository jekyll/jekyll, pull requests merged in 2019-06, with the labels that each got.

#7690 Backport #7213 and #7633 for v3.8.x: Fix broken include_relative usage in excerpt
  features/include_relative_tag.feature
  lib/jekyll/tags/include.rb
Labels: :rewind: backport, fix

#7706 Do not install docs on updating gems on Travis
  .travis.yml
Labels: meta

#7708 fix link to Site Source config
  docs/_docs/github-pages.md
Labels: documentation

#7709 Update TestTags in sync with Rouge v3.4
  test/test_tags.rb
Labels: tests

#7707 Refactor `EntryFilter#glob_include?`
  lib/jekyll/entry_filter.rb
  test/test_entry_filter.rb
Labels: refactor

#7705 Reject entries that are just dots in a directory
  lib/jekyll/entry_filter.rb
Labels: fix

#7702 Use regexp to filter special entries
  lib/jekyll/entry_filter.rb
Labels: fix

#7711 Don't read symlinks in site.include in safe mode
  lib/jekyll/reader.rb
Labels: security

#7718 Replace `String#=~` with `String#match?`
  lib/jekyll/tags/include.rb
Labels: optimization :zap:

#7722 Backport #7697 for v3.8.x: Memoize SiteDrop#documents to reduce allocations
  lib/jekyll/drops/site_drop.rb
Labels: :rewind: backport, fix

#7723 Replace `String#=~` with `String#match?`
  lib/jekyll/utils.rb
Labels: fix
