Repository jekyll/jekyll, pull requests merged in 2019-07, with the labels that each got.

#7679 Update log output for an invalid theme directory
  Gemfile
  features/theme.feature
  lib/jekyll/theme.rb
  test/fixtures/test-theme-skinny/_layouts/default.html
  test/fixtures/test-theme-skinny/_layouts/home.html
  test/fixtures/test-theme-skinny/test-theme-skinny.gemspec
Labels: backport-candidate, fix, themes :art:

#7734 Backport #7679 for v3.8.x: Update log output for an invalid theme directory
  Gemfile
  History.markdown
  features/theme.feature
  lib/jekyll/theme.rb
  test/fixtures/test-theme-skinny/_layouts/default.html
  test/fixtures/test-theme-skinny/_layouts/home.html
  test/fixtures/test-theme-skinny/test-theme-skinny.gemspec
Labels: :rewind: backport, fix

#7735 Create 3.8.6 release notes
  History.markdown
  docs/_docs/history.md
  docs/_posts/2019-07-02-jekyll-3-8-6-released.markdown
Labels: release

#7737 Move updates from generated file to source file
  .github/CONTRIBUTING.markdown
  docs/_docs/contributing.md
Labels: documentation, fix

#7749 Reduce Array objects generated from utility method
  lib/jekyll/utils.rb
Labels: internal, optimization :zap:

#7720 Add recursive navigation tutorial
  docs/_tutorials/navigation.md
Labels: documentation

#7761 Replace redundant Array#map with Array#each
  lib/jekyll/readers/page_reader.rb
Labels: fix, internal
