Repository jekyll/jekyll, pull requests merged in 2019-02, with the labels that each got.

#7510 Hosting with AWS Amplify
  docs/_docs/deployment/third-party.md
Labels: documentation

#7518 Test with Ruby 2.6 on AppVeyor [skip travis]
  appveyor.yml
Labels: tests, windows

#7520 Notify users on Windows to use tzinfo-1.x series
  docs/_docs/installation/windows.md
Labels: documentation, windows

#7232 Configure cache_dir
  features/cache.feature
  lib/jekyll/cache.rb
  lib/jekyll/site.rb
  test/test_site.rb
Labels: enhancement

#7530 Docs: check if var exists before include tag
  docs/_docs/includes.md
Labels: documentation

#7427 Allow custom sorting of collection documents
  docs/_docs/collections.md
  features/collections.feature
  features/collections_dir.feature
  features/step_definitions.rb
  lib/jekyll/collection.rb
  test/source/_tutorials/dive-in-and-publish-already.md
  test/source/_tutorials/extending-with-plugins.md
  test/source/_tutorials/getting-started.md
  test/source/_tutorials/graduation-day.md
  test/source/_tutorials/lets-roll.md
  test/source/_tutorials/tip-of-the-iceberg.md
  test/test_collections.rb
Labels: feature

#7538 Clarify docs on collections regarding the need for front matter
  docs/_docs/collections.md
Labels: documentation

#7188 Always exclude certain paths from being processed
  docs/_docs/upgrading/3-to-4.md
  features/site_configuration.feature
  lib/jekyll/configuration.rb
  lib/jekyll/entry_filter.rb
  lib/jekyll/reader.rb
  lib/site_template/_config.yml
  test/test_configuration.rb
Labels: breaking-change, enhancement

#7540 Add a script to profile docs with CI
  .travis.yml
  appveyor.yml
  script/profile-docs
Labels: fix, internal, profiling, tests

#7525 Fix incorrect Windows path in themes.md
  docs/_docs/themes.md
Labels: documentation, windows

#7521 Upgrade WinTZ utility to use TZInfo-2.0
  Gemfile
  docs/_docs/upgrading/3-to-4.md
  lib/jekyll/commands/new.rb
  lib/jekyll/utils/win_tz.rb
Labels: enhancement, windows
