Repository jekyll/jekyll, pull requests merged in 2019-01, with the labels that each got.

#7438 Test with the new Ruby v2.6
  .travis.yml
Labels: tests

#7449 Bump RuboCop to v0.62.x
  Gemfile
Labels: dependency

#7448 Fix Interpreter warning from Jekyll::Renderer
  lib/jekyll/renderer.rb
Labels: fix

#7410 Dont write static files from unrendered collection
  features/collections.feature
  lib/jekyll/static_file.rb
Labels: fix

#7382 Excerpt handling of custom and intermediate tags
  lib/jekyll/excerpt.rb
  test/source/_plugins/custom_block.rb
  test/source/_posts/2018-11-15-excerpt-liquid-block.md
  test/test_excerpt.rb
  test/test_generated_site.rb
Labels: accepted, backport-candidate, fix

#7459 Permalink docs typo fixes
  docs/_docs/permalinks.md
Labels: documentation

#7464 Grammatical correction
  docs/_docs/contributing.md
Labels: documentation

#7473 Docs: store SSL key and cert in site source
  docs/_docs/configuration/options.md
Labels: documentation

#6998 Support for binary operators in where_exp filter
  lib/jekyll/filters.rb
  test/test_filters.rb
Labels: enhancement
