Repository jekyll/jekyll, pull requests merged in 2020-09, with the labels that each got.

#8369 Configure Performance cops
  .rubocop.yml
  test/test_filters.rb
  test/test_front_matter_defaults.rb
Labels: internal

#8358 Simplifying the Git post-receive hook-example
  docs/_docs/deployment/automated.md
Labels: documentation

#8313 Update rubocop gem to 0.90.0
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  lib/jekyll/commands/doctor.rb
  lib/jekyll/commands/new_theme.rb
  lib/jekyll/document.rb
  lib/jekyll/filters.rb
  lib/jekyll/tags/post_url.rb
  test/helper.rb
  test/test_tags.rb
Labels: accepted

#8375 Fix path matching regex in post_url Liquid tag
  features/post_url_tag.feature
  features/support/helpers.rb
  lib/jekyll/tags/post_url.rb
Labels: fix

#8377 Use data file to render table at `/docs/configuration/options/#global-configuration`
  docs/_data/config_options.yml
  docs/_docs/configuration/options.md
Labels: documentation

#8383 Improve maintainability of config option data
  docs/_data/config_options.yml
  docs/_data/config_options/build.yml
  docs/_data/config_options/global.yml
  docs/_data/config_options/serve.yml
  docs/_docs/configuration/options.md
Labels: documentation

#7236 Refactor Jekyll::Utils::Platforms
  lib/jekyll/utils/platforms.rb
Labels: refactor

#8387 Reduce string allocations from the `link` tag
  lib/jekyll/tags/link.rb
Labels: optimization :zap:, refactor

#8192 Optimize parsing of parameters in include tag
  benchmark/parse-include-tag-params.rb
  lib/jekyll/tags/include.rb
Labels: optimization :zap:

#8398 Add workflow to build and profile third-party repo
  .github/workflows/actions/memprof.rb
  .github/workflows/third-party.yml
Labels: github

#8392 Reduce string allocations from generating doc URLs
  lib/jekyll/url.rb
Labels: memory-optimization :zap:

#8183 Implement custom delegators for drop methods
  benchmark/static-drop-vs-forwarded.rb
  lib/jekyll/drops/collection_drop.rb
  lib/jekyll/drops/document_drop.rb
  lib/jekyll/drops/drop.rb
  lib/jekyll/drops/site_drop.rb
  lib/jekyll/drops/static_file_drop.rb
  lib/jekyll/drops/url_drop.rb
Labels: feature, memory-optimization :zap:, optimization :zap:

#8401 Check if site is in incremental mode optimally
  lib/jekyll/tags/include.rb
Labels: fix

#8415 Handle nil argument to Jekyll.sanitized_path
  lib/jekyll.rb
  test/test_path_sanitization.rb
Labels: fix

#8418 Fix test suite compatibility with JRuby
  Gemfile
Labels: dependency, tests
