Repository jekyll/jekyll, pull requests merged in 2020-11, with the labels that each got.

#8451 Memoize defaults computed for Convertibles
  lib/jekyll/convertible.rb
Labels: micro-optimization

#8453 Reduce array allocations from merging categories
  lib/jekyll/document.rb
Labels: memory-optimization :zap:

#8456 docs: installation: fedora: add additional dependencies
  docs/_docs/installation/other-linux.md
  docs/_docs/troubleshooting.md
Labels: documentation

#8457 Enable Lint/NoReturnInBeginEndBlocks Cop
  .rubocop.yml
  lib/jekyll/path_manager.rb
Labels: bug, fix

#8458 Memoize destination of pages, documents and staticfiles
  lib/jekyll/document.rb
  lib/jekyll/page.rb
  lib/jekyll/static_file.rb
Labels: memory-optimization :zap:, micro-optimization

#8459 Enhance detection of conflicting destination URLs
  features/permalinks.feature
  lib/jekyll/commands/doctor.rb
Labels: enhancement

#8463 Generate items from `site.include` list only once
  features/site_configuration.feature
  lib/jekyll/reader.rb
Labels: bug, fix

#8465 Allow triggering `:post_convert` events atomically
  features/hooks.feature
  lib/jekyll/hooks.rb
Labels: fix

#8100 Debug reading Page and Layout objects
  lib/jekyll/convertible.rb
Labels: enhancement

#8292 Test that Liquid expressions are not deeply evaled
  features/rendering.feature
Labels: tests

#7414 Test rendering arbitrary Liquid variables by default
  features/rendering.feature
Labels: tests

#8467 Improve documentation on Hooks in Jekyll
  docs/_docs/plugins/hooks.md
  docs/_sass/_style.scss
Labels: documentation

#8472 Explicitly return nil after site process phase
  lib/jekyll/site.rb
  test/test_site.rb
Labels: bug, fix

#8473 Add custom debug strings for Jekyll objects
  lib/jekyll/layout.rb
  lib/jekyll/site.rb
Labels: enhancement

#8481 Debug reading data files in a site
  lib/jekyll/readers/data_reader.rb
Labels: enhancement
