Repository jekyll/jekyll, pull requests merged in 2020-10, with the labels that each got.

#8403 Utilize flexibility of Site#in_dest_dir
  lib/jekyll/document.rb
  lib/jekyll/static_file.rb
Labels: fix, memory-optimization :zap:, optimization :zap:

#8400 Reduce allocation from normalize_whitespace filter
  lib/jekyll/filters.rb
Labels: memory-optimization :zap:

#8424 Cache Jekyll.sanitized_path
  lib/jekyll.rb
  lib/jekyll/path_manager.rb
  test/test_path_manager.rb
Labels: optimization :zap:, refactor

#8427 Use Regexp#match? when MatchData is not required
  lib/jekyll/cleaner.rb
Labels: micro-optimization

#8393 Check default front matter scope against symbols
  lib/jekyll/frontmatter_defaults.rb
Labels: memory-optimization :zap:

#8394 Stash frequently used Drop setter keys for reuse
  lib/jekyll/drops/drop.rb
Labels: memory-optimization :zap:

#8421 Memoize array of drop getter method names
  lib/jekyll/drops/drop.rb
  test/test_drop.rb
Labels: memory-optimization :zap:, optimization :zap:

#8447 Add links to all Jekyll themes on GitHub tagged with #jekyll-theme
  docs/_docs/themes.md
  docs/pages/resources.md
Labels: documentation
