Repository jekyll/jekyll, pull requests merged in 2020-04, with the labels that each got.

#8089 Utilize relative_url filter in documentation site
  docs/_docs/assets.md
  docs/_docs/collections.md
  docs/_docs/community/community.md
  docs/_docs/configuration.md
  docs/_docs/configuration/environments.md
  docs/_docs/configuration/front-matter-defaults.md
  docs/_docs/configuration/options.md
  docs/_docs/contributing.md
  docs/_docs/datafiles.md
  docs/_docs/deployment.md
  docs/_docs/deployment/automated.md
  docs/_docs/front-matter.md
  docs/_docs/github-pages.md
  docs/_docs/index.md
  docs/_docs/installation.md
  docs/_docs/installation/macos.md
  docs/_docs/installation/windows.md
  docs/_docs/liquid.md
  docs/_docs/liquid/tags.md
  docs/_docs/plugins.md
  docs/_includes/docs_contents.html
  docs/_includes/docs_contents_mobile.html
  docs/_includes/footer.html
  docs/_includes/header.html
  docs/_includes/mobile-nav-items.html
  docs/_includes/news_contents.html
  docs/_includes/news_contents_mobile.html
  docs/_includes/news_item.html
  docs/_includes/news_item_archive.html
  docs/_includes/primary-nav-items.html
  docs/_includes/section_nav_tutorials.html
  docs/_includes/top.html
  docs/_includes/tutorials_contents.html
  docs/_includes/tutorials_contents_mobile.html
  docs/_layouts/news_item.html
  docs/_tutorials/index.md
  docs/pages/404.html
  docs/pages/index.html
  docs/pages/resources.md
  docs/pages/showcase.html
Labels: site

#8064 Simplify `Jekyll::Renderer#validate_layout`
  lib/jekyll/renderer.rb
Labels: refactor

#8092 Render tutorial metadata in documentation site
  docs/_layouts/tutorials.html
  docs/_sass/_style.scss
  docs/_tutorials/cache-api.md
  docs/_tutorials/convert-site-to-jekyll.md
  docs/_tutorials/custom-404-page.md
  docs/_tutorials/navigation.md
  docs/_tutorials/orderofinterpretation.md
  docs/_tutorials/using-jekyll-with-bundler.md
  docs/_tutorials/video-walkthroughs.md
Labels: site

#8090 Create CSV to table tutorial
  docs/_data/tutorials.yml
  docs/_tutorials/csv-to-table.md
Labels: tutorial

#8098 Add version badge for Custom Sorting of Documents
  docs/_docs/collections.md
Labels: documentation

#8097 Docs: Fix grammar in `_docs/front-matter.md`
  docs/_docs/front-matter.md
Labels: documentation

#7570 Reduce Jekyll::Renderer instances during a build
  lib/jekyll/convertible.rb
  lib/jekyll/document.rb
  lib/jekyll/site.rb
Labels: internal

#7908 Add static file's basename to its url_placeholder
  features/collections.feature
  lib/jekyll/static_file.rb
  test/source/_methods/extensionless_static_file
Labels: fix, priority 1 (must)

#7967 Clear cached Liquid template scope before render
  lib/jekyll/liquid_renderer/file.rb
Labels: fix, priority 1 (must)

#8094 Add slugified_categories URL placeholder
  docs/_docs/permalinks.md
  features/post_data.feature
  lib/jekyll/drops/url_drop.rb
Labels: feature

#7990 Cache URLFilter results of string inputs per site
  lib/jekyll/filters/url_filters.rb
  lib/jekyll/site.rb
  test/test_filters.rb
Labels: optimization :zap:, priority 2 (should)

#8125 Backport #7948 for v3.8.x
  .rubocop.yml
  .travis.yml
  appveyor.yml
  lib/jekyll/convertible.rb
  lib/jekyll/document.rb
  lib/jekyll/tags/include.rb
  script/profile-docs
Labels: :rewind: backport

#8124 Backport #7948 for v4.0.x
  .rubocop.yml
  .travis.yml
  lib/jekyll/convertible.rb
  lib/jekyll/document.rb
  lib/jekyll/tags/include.rb
  test/test_document.rb
  test/test_filters.rb
Labels: :rewind: backport

#8143 Fix Kramdown converter based tests for v4.0.x
  features/post_excerpts.feature
  test/test_kramdown.rb
Labels: :rewind: backport, tests

#8141 Backport #7967 for v4.0.x
  lib/jekyll/liquid_renderer/file.rb
Labels: :rewind: backport, fix

#8142 Backport #7908 for v4.0.x
  features/collections.feature
  lib/jekyll/static_file.rb
  test/source/_methods/extensionless_static_file
Labels: :rewind: backport, fix

#8119 Docs: Deploy Jekyll site with GitHub Actions
  docs/_docs/continuous-integration/github-actions.md
  docs/_docs/deployment/automated.md
Labels: documentation

#8138 Escape regex characters in paths to match
  test/test_convertible.rb
Labels: fix, internal, tests

#8140 Use platforms instead of install_if
  Gemfile
  lib/jekyll/commands/new.rb
Labels: fix

#8113 Config include trailing slash
  lib/jekyll/entry_filter.rb
  test/source/_glob_include_test/_is_dir/include_me.txt
  test/source/_glob_include_test/_not_dir
  test/test_entry_filter.rb
Labels: fix

#8150 Clarify `bundle config` in Bundler tutorial
  docs/_tutorials/using-jekyll-with-bundler.md
Labels: documentation

#7950 Allow extensionless document in a strict site
  features/collections.feature
  lib/jekyll/document.rb
Labels: fix, priority 3 (could)

#8035 Configure default language for syntax-highlighting
  features/collections.feature
  lib/jekyll/converters/markdown/kramdown_parser.rb
  test/test_kramdown.rb
Labels: enhancement, priority 3 (could)

#8042 Remove dev dependencies from new theme-gem gemspec
  lib/theme_template/theme.gemspec.erb
Labels: enhancement, priority 2 (should), themes :art:
