Repository jekyll/jekyll, pull requests merged in 2020-03, with the labels that each got.

#8044 Simplify Jekyll::Hooks.trigger logic
  lib/jekyll/hooks.rb
Labels: refactor

#8047 Allow multiple binary operators in where_exp filter
  lib/jekyll/filters.rb
  test/test_filters.rb
Labels: fix

#8028 Fix documents custom-ordering logic
  lib/jekyll/collection.rb
Labels: fix, priority 1 (must)

#8063 Remove extra paragraph tags
  docs/_docs/step-by-step/08-blogging.md
Labels: documentation

#8069 Use `layout.path` when rendering the Liquid layout
  lib/jekyll/renderer.rb
Labels: fix

#7992 Add PageDrop to provide Liquid templates with data
  docs/_docs/pages.md
  lib/jekyll/drops/page_drop.rb
  lib/jekyll/page.rb
  test/test_page.rb
  test/test_page_without_a_file.rb
Labels: enhancement, priority 3 (could)

#8041 Optimize `Kramdown::JekyllDocument#to_html` calls
  lib/jekyll/converters/markdown/kramdown_parser.rb
Labels: micro-optimization

#8067 Reduce Pathname objects from front matter defaults
  lib/jekyll/frontmatter_defaults.rb
Labels: optimization :zap:

#8081 Add default front matter for tutorials collection
  docs/_config.yml
  docs/_tutorials/cache-api.md
  docs/_tutorials/convert-site-to-jekyll.md
  docs/_tutorials/custom-404-page.md
  docs/_tutorials/index.md
  docs/_tutorials/navigation.md
  docs/_tutorials/orderofinterpretation.md
  docs/_tutorials/using-jekyll-with-bundler.md
  docs/_tutorials/video-walkthroughs.md
Labels: site

#8083 Reduce array allocations from `StaticFile#path`
  lib/jekyll/static_file.rb
Labels: micro-optimization
