Repository jekyll/jekyll, pull requests merged in 2020-05, with the labels that each got.

#8147 docs: update your-first-plugin.md
  docs/_docs/plugins/your-first-plugin.md
Labels: documentation

#8160 Backport #7878 for v4.0.x
  lib/jekyll/filters.rb
  test/test_filters.rb
Labels: :rewind: backport, fix

#8131 Allow disabling import of theme configuration
  docs/_docs/configuration/options.md
  features/theme_configuration.feature
  lib/jekyll/site.rb
Labels: enhancement

#8075 Improve path normalization in liquid_renderer
  lib/jekyll/liquid_renderer.rb
  lib/jekyll/theme.rb
  test/test_liquid_renderer.rb
Labels: fix

#8166 Release: v4.0.1 post
  docs/_posts/2020-05-08-jekyll-4-0-1-released.markdown
  docs/latest_version.txt
Labels: release

#8168 chore(ci): cache dependencies
  .github/workflows/ci.yml
Labels: tests

#8170 Site: Filter through just the docs collection
  docs/_includes/docs_contents.html
  docs/_includes/docs_contents_mobile.html
Labels: optimization :zap:, site

#8165 Provide invokables for common drop query keys
  lib/jekyll/drops/document_drop.rb
  lib/jekyll/drops/page_drop.rb
Labels: internal, optimization :zap:

#8154 Optimize path sanitization of default front matter
  lib/jekyll/frontmatter_defaults.rb
Labels: optimization :zap:

#8167 Switch slugify regex to support more Unicode character groups
  lib/jekyll/utils.rb
  test/test_utils.rb
Labels: fix

#8177 Check if entry is a directory once per enumerator
  lib/jekyll/entry_filter.rb
Labels: fix, optimization :zap:

#8196 Improve documentation on tags and categories
  docs/_docs/posts.md
Labels: documentation

#7642 Allow excerpts to be generated for Page objects
  lib/jekyll.rb
  lib/jekyll/drops/page_drop.rb
  lib/jekyll/page.rb
  lib/jekyll/page_excerpt.rb
  test/test_page.rb
  test/test_page_without_a_file.rb
Labels: enhancement, feature

#6760 Profile various stages of a site's build process
  .rubocop.yml
  lib/jekyll.rb
  lib/jekyll/liquid_renderer/table.rb
  lib/jekyll/profiler.rb
  lib/jekyll/site.rb
Labels: profiling

#8171 Add find filters to optimize where-first chains
  benchmark/find-filter-vs-where-first-filters.rb
  docs/_data/jekyll_filters.yml
  lib/jekyll/filters.rb
  test/test_filters.rb
Labels: feature

#8126 Add a workflow to build and deploy docs site
  .github/actions/bootstrap
  .github/actions/deploy_docs
  .github/workflows/deploy_docs.yml
Labels: github, site

#8188 Initialize static files' data hash only if needed
  lib/jekyll/static_file.rb
Labels: internal, optimization :zap:

#8158 Initialize include-files as Jekyll objects
  lib/jekyll.rb
  lib/jekyll/inclusion.rb
  lib/jekyll/site.rb
  lib/jekyll/tags/include.rb
Labels: internal, optimization :zap:

#8209 Prepare for release of `v4.1.0`
  History.markdown
  docs/_docs/history.md
  docs/_posts/2020-05-27-jekyll-4-1-0-released.markdown
Labels: release

#8213 Add atom:link rel="self" to RSS feed template
  docs/_tutorials/convert-site-to-jekyll.md
Labels: documentation, tutorial
