Repository jekyll/jekyll, pull requests merged in 2020-02, with the labels that each got.

#7989 Correct documentation of filters
  docs/_docs/plugins/filters.md
Labels: documentation

#7870 Document sorting two documents by their `date`
  docs/_docs/collections.md
Labels: documentation

#7821 Test where filter handling numeric property values
  test/test_filters.rb
Labels: tests

#7865 Include _config.yml in a new theme's gemspec
  features/step_definitions.rb
  features/theme_gem.feature
  lib/theme_template/theme.gemspec.erb
Labels: fix, needs-decision :thinking:

#7696 Optimize Jekyll::Filters#item_property
  .rubocop.yml
  lib/jekyll/filters.rb
Labels: internal, optimization :zap:

#7413 Update 07-assets.md
  docs/_docs/step-by-step/07-assets.md
Labels: documentation

#8012 chore(deps): rubocop 0.80.0
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
Labels: internal

#8014 Update unit tests for Kramdown-based converter
  test/test_kramdown.rb
Labels: tests

#8016 Add Visual Studio Code Development Container
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  docs/_docs/contributing.md
  docs/_docs/installation.md
Labels: internal

#7928 Add an option to easily disable disk-cache
  docs/_docs/configuration/options.md
  features/cache.feature
  lib/jekyll/command.rb
  lib/jekyll/site.rb
Labels: feature

#8015 Configure kramdown toc_levels as array by default
  docs/_docs/configuration/default.md
  lib/jekyll/configuration.rb
Labels: micro-optimization

#8020 Optimize rendering of the documentation site
  docs/_includes/analytics.html
  docs/_includes/docs_contents.html
  docs/_includes/docs_contents_mobile.html
  docs/_includes/docs_variables_table.html
  docs/_includes/header.html
  docs/_includes/mobile-nav-items.html
  docs/_includes/news_contents.html
  docs/_includes/news_contents_mobile.html
  docs/_includes/news_item.html
  docs/_includes/primary-nav-items.html
  docs/_includes/section_nav_tutorials.html
  docs/_includes/step-index.html
  docs/_includes/tutorials_contents.html
  docs/_includes/tutorials_contents_mobile.html
  docs/_includes/tutorials_option.html
  docs/_includes/tutorials_ul.html
  docs/_layouts/default.html
  docs/_layouts/docs.html
  docs/_layouts/news.html
  docs/_layouts/news_item.html
  docs/_layouts/page.html
  docs/_layouts/step.html
  docs/_layouts/tutorials.html
  docs/pages/404.html
  docs/pages/news.html
  docs/pages/releases.html
  docs/pages/showcase.html
Labels: optimization :zap:, site

#8013 Optimize markdown parsing with Kramdown by reusing the options and parser objects
  lib/jekyll/converters/markdown/kramdown_parser.rb
Labels: friction, optimization :zap:

#8032 Docs: Render full contents of just the latest post
  docs/_includes/news_item.html
  docs/_includes/news_item_archive.html
  docs/_layouts/news_item.html
  docs/_sass/_style.scss
  docs/pages/news.html
  docs/pages/releases.html
Labels: site
