Repository jekyll/jekyll, pull requests merged in 2020-07, with the labels that each got.

#8282 Move permalink styles data to constant
  lib/jekyll/configuration.rb
Labels: internal, refactor

#8287 Update rubocop gem to 0.87.1
  .rubocop.yml
  Gemfile
Labels: internal

#8291 Add a note on the rendering process in the docs
  docs/_data/docs_nav.yml
  docs/_docs/rendering-process.md
Labels: documentation
