Repository jekyll/jekyll, pull requests merged in 2020-12, with the labels that each got.

#8485 Reduce allocations from computing item property
  lib/jekyll/filters.rb
Labels: optimization :zap:

#8414 Add Arengu to form services list documentation
  docs/pages/resources.md
Labels: documentation

#8489 Optimize Page#dir with a private method
  lib/jekyll/page.rb
Labels: optimization :zap:

#8492 Migrate TravisCI jobs to GitHub Actions
  .github/workflows/ci.disabled_workflow
  .github/workflows/ci.yml
  .travis.yml
  README.markdown
Labels: github, internal, tests

#8504 fix: showcase
  docs/_config.yml
  docs/_data/showcase.yml
  docs/pages/showcase.html
Labels: site

#8497 Stash attribute hash for Liquid computed for pages
  lib/jekyll/convertible.rb
Labels: memory-optimization :zap:

#8466 Release: Jekyll 4.2.0
  History.markdown
  docs/_config.yml
  docs/_docs/history.md
  docs/_posts/2020-12-14-jekyll-4-2-0-released.markdown
  docs/latest_version.txt
  lib/jekyll/version.rb
Labels: release

#8518 typo - do instead of don't
  docs/_docs/installation/windows.md
Labels: documentation

#8488 Document support for TSV files consistently
  docs/_docs/datafiles.md
Labels: documentation
