Repository jekyll/jekyll, pull requests merged in 2021-08, with the labels that each got.

#8756 Respect collections_dir config within include tag
  features/incremental_rebuild.feature
  lib/jekyll/tags/include.rb
Labels: fix

#8623 Tags:Highlight: Decomposed HTMLLegacy formatter
  lib/jekyll/tags/highlight.rb
Labels: refactor

#8786 Fix regression in Convertible module from v4.2.0
  features/rendering.feature
  lib/jekyll/convertible.rb
Labels: fix

#8795 Backport #8756 to 3.9-stable
  features/incremental_rebuild.feature
  lib/jekyll/tags/include.rb
Labels: fix, :rewind: backport
