Repository jekyll/jekyll, pull requests merged in 2021-01, with the labels that each got.

#8527 Improve documentation on developing generators
  docs/_docs/plugins/generators.md
Labels: documentation

#8524 Add webrick as a dependency
  .github/workflows/ci.yml
  jekyll.gemspec
  test/test_generated_site.rb
Labels: fix

#8538 style: enable new cops
  .rubocop.yml
  Gemfile
  benchmark/schwartzian_transform.rb
  test/helper.rb
  test/test_ansi.rb
  test/test_cleaner.rb
  test/test_collections.rb
  test/test_commands_serve.rb
  test/test_configuration.rb
  test/test_doctor_command.rb
  test/test_document.rb
  test/test_drop.rb
  test/test_entry_filter.rb
  test/test_excerpt.rb
  test/test_filters.rb
  test/test_front_matter_defaults.rb
  test/test_kramdown.rb
  test/test_page.rb
  test/test_page_without_a_file.rb
  test/test_plugin_manager.rb
  test/test_regenerator.rb
  test/test_sass.rb
  test/test_site.rb
  test/test_site_drop.rb
  test/test_static_file.rb
Labels: style, tests

#8399 Step By Step Instructions Review
  docs/_docs/step-by-step/01-setup.md
  docs/_docs/step-by-step/02-liquid.md
  docs/_docs/step-by-step/03-front-matter.md
  docs/_docs/step-by-step/04-layouts.md
Labels: documentation
