Repository jekyll/jekyll, pull requests merged in 2021-09, with the labels that each got.

#8620 Revert #7253: "Don't reset site.url to localhost:4000 by default"
  docs/_docs/step-by-step/01-setup.md
  docs/_docs/step-by-step/10-deployment.md
  lib/jekyll/commands/serve.rb
  test/test_commands_serve.rb
Labels: backport-candidate

#8793 Backport #8786 for v4.2.x: Fix regression in Convertible module from v4.2.0
  features/rendering.feature
  lib/jekyll/convertible.rb
Labels: fix, :rewind: backport

#8794 Backport #8756 for v4.2.x: Respect collections_dir config within include tag
  features/incremental_rebuild.feature
  lib/jekyll/tags/include.rb
Labels: fix, :rewind: backport

#8808 Backport #8620 for v4.2.x: Revert #7253: "Don't reset site.url to localhost:4000 by default"
  docs/_docs/step-by-step/01-setup.md
  docs/_docs/step-by-step/10-deployment.md
  lib/jekyll/commands/serve.rb
  test/test_commands_serve.rb
Labels: fix, :rewind: backport

#8798 Always hide cache-dir contents from Git
  lib/jekyll/site.rb
  test/test_site.rb
Labels: enhancement
