Repository jekyll/jekyll, pull requests merged in 2021-05, with the labels that each got.

#8654 style: run rubocop -a
  lib/jekyll/cache.rb
Labels: style

#8587 Add documentation for Sass configuration options
  docs/_docs/assets.md
  docs/_docs/configuration.md
  docs/_docs/configuration/default.md
  docs/_docs/configuration/sass.md
Labels: documentation

#8614 Use official Ruby setup GH action
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/third-party.yml
Labels: internal, tests

#8585 Load Jekyll plugins from BUNDLE_GEMFILE location
  lib/jekyll/plugin_manager.rb
  test/test_plugin_manager.rb
Labels: fix

#8680 fix(security): CVE-2021-28834
  jekyll.gemspec
Labels: dependency, fix, security

#8681 Improve the "Markdown Options" Docs
  .github/actions/spelling/expect.txt
  docs/_docs/configuration/markdown.md
Labels: documentation
