Repository jekyll/jekyll, pull requests merged in 2023-01, with the labels that each got.

#9254 Backport #9223 for 4.3.x: Update sass related tests for jekyll-sass-converter 3.x
  features/rendering.feature
  features/theme.feature
  test/test_filters.rb
  test/test_sass.rb
  test/test_theme_assets_reader.rb
Labels: internal, :rewind: backport

#9255 Backport #9186 for v4.3.x: Remove totals in profile table properly
  lib/jekyll/liquid_renderer/table.rb
  lib/jekyll/profiler.rb
Labels: fix, :rewind: backport

#9256 Backport #9187 for v4.3.x: Optimize `Site#each_site_file`
  lib/jekyll/site.rb
Labels: fix, :rewind: backport

#9257 Rename sass partial created for new blank site
  features/create_sites.feature
  lib/blank_template/_sass/base.scss
  lib/blank_template/assets/css/main.scss
Labels: fix, backport-candidate

#9262 Backport #9257 for v4.3.x: Rename sass partial created for new blank site
  features/create_sites.feature
  lib/blank_template/_sass/base.scss
  lib/blank_template/assets/css/main.scss
Labels: fix, :rewind: backport

#9272 v3.9.x: test under Ruby 3.2
  .github/workflows/ci.yml
Labels: Jekyll 3.x

#9269 3.9.x: Support i18n 1.x
  jekyll.gemspec
Labels: Jekyll 3.x

#9245 Grammatical reordering in 3-to-4 upgrading docs
  docs/_docs/upgrading/3-to-4.md
Labels: documentation

#9264 fixed grammatical mistake on "showcase" page
  docs/pages/showcase.html
Labels: documentation

#9280 Backport #8880 for v3.9.x: Support both tzinfo v1 and v2 alongwith non-half hour offsets
  Gemfile
  appveyor.yml
  docs/_docs/windows.md
  features/site_configuration.feature
  lib/jekyll/commands/new.rb
  lib/jekyll/utils/win_tz.rb
  test/test_win_tz.rb
Labels: :rewind: backport

#9282 Release :gem: v3.9.3
  History.markdown
  docs/_config.yml
  docs/_docs/history.md
  docs/_posts/2023-01-27-jekyll-3-9-3-released.markdown
  docs/latest_version.txt
  lib/jekyll/version.rb
Labels: Jekyll 3.x
