Repository jekyll/jekyll, pull requests merged in 2023-12, with the labels that each got.

#9285 Backport #9237 to 4.3-stable "test: use hash explicitly for Struct initializer for ruby 3.2"
  test/test_filters.rb
Labels: in-limbo

#9514 Add Ruby 3.3 to Jekyll 3.9.x test matrix
  .github/workflows/ci.yml
Labels: Jekyll 3.x

#9513 Backport logger-1.4.3 from #9392 to 3.9-stable
  lib/jekyll/stevenson.rb
Labels: fix, :rewind: backport, bug :bug:, Jekyll 3.x

#9515 Add Jekyll 3.9.4 release post and changelog
  History.markdown
  docs/_docs/history.md
  docs/_posts/2023-12-28-jekyll-3-9-4-released.markdown
Labels: documentation

#9512 Fix Performance/StringIdentifierArgument violation in site.rb and allow activesupport 6 for windows tests
  Gemfile
  lib/jekyll/site.rb
Labels: refactor
